{% set name = "import-linter" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/import-linter-{{ version }}.tar.gz
  sha256: fe63a68d023af46ba853923e643d0f5e802c0b974fae9ce5654962c31c873784

build:
  entry_points:
    - lint-imports = importlinter.cli:lint_imports_command
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - click >=6
    - grimp >=2.0
    - typing-extensions >=3.10.0.0
    - tomli >=1.2.1

test:
  imports:
    - importlinter
  commands:
    - pip check
    - lint-imports --help
  requires:
    - pip

about:
  home: https://pypi.org/project/import-linter/
  summary: Enforces rules for the imports within and between Python packages.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
