{% set name = "import-linter" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/import-linter-{{ version }}.tar.gz
  sha256: 392a3a6b1eed22cd35fa336c30d115c2e8a29b937a7aebc74274ece065bd880e

build:
  entry_points:
    - lint-imports = importlinter.cli:lint_imports_command
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click >=6
    - grimp >=3.0
    - tomli >=1.2.1
    - typing-extensions >=3.10.0.0

test:
  imports:
    - importlinter
  commands:
    - pip check
    - lint-imports --help
  requires:
    - pip

about:
  home: https://pypi.org/project/import-linter/
  summary: Enforces rules for the imports within and between Python packages.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
